import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Wishlist from "./pages/WIshlist.tsx/Wishlist";
import Wishlist_cc from "@/components/Wishlist_c/Wishlist_cc";
import Wishlist_c from "@/components/Wishlist_c/Wishlist_c";
import Cart from "./pages/Cart/Cart";
import Cart_c from "@/components/Cart_c/Cart_c";
import Cart_cc from "@/components/Cart_c/Cart_cc";
import Checkout from "./pages/Checkout/Checkout";
import Checkout_c from "@/components/Checkout_c/Checkout_c";
import Contact from "./pages/Contact/Contact";
import Faq from "./pages/Faq/Faq";
import Notfound from "./pages/404/Notfound";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Miralou",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar /> */}
        {/* <Wishlist /> */}
        {/* <Wishlist_c /> */}
        {/* <Wishlist_cc /> */}
        {/* <Cart /> */}
        {/* <Cart_c /> */}
        {/* <Cart_cc /> */}
        {/* <Checkout /> */}
        {/* <Contact /> */}
        {/* <Faq /> */}
        <Notfound />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
